# Development Dockerfile for Serendipity Web Service
FROM golang:1.24.5

WORKDIR /app

RUN go install github.com/air-verse/air@v1.61.5

COPY go.mod go.sum ./
RUN go mod download

COPY . .

EXPOSE 4000

CMD ["air", "-c", ".air.toml"]
